class CreateForecastInputs < ActiveRecord::Migration[6.0]
  def change
    create_table :forecast_inputs do |t|
      t.integer :forecast_id
      t.float :inflation
      t.float :starting_value
      t.float :income
      t.float :spend_value
      t.integer :years_income
      t.integer :years_forecast
      t.integer :portfolio1_id
      t.integer :portfolio2_id
      t.float :weight_port1
      t.float :weight_port2
      t.integer :cma_id
      t.integer :correlation_id
      t.float :year1_cf
      t.float :year2_cf
      t.string :year3_cf
      t.float :year4_cf
      t.float :year5_cf
      t.float :year6_cf
      t.float :year7_cf
      t.float :year8_cf
      t.float :year9_cf
      t.float :year10_cf
      t.float :year11_cf
      t.float :year12_cf
      t.float :year13_cf
      t.float :year14_cf
      t.float :year15_cf
      t.float :year16_cf
      t.float :year17_cf
      t.float :year18_cf
      t.float :year19_cf
      t.float :year20_cf
      t.float :year21_cf
      t.float :year22_cf
      t.float :year23_cf
      t.float :year24_cf
      t.float :year25_cf
      t.float :year26_cf
      t.float :year27_cf
      t.float :year28_cf
      t.float :year29_cf
      t.float :year30_cf
      t.integer :year1_cma_id
      t.integer :year2_cma_id
      t.integer :year3_cma_id
      t.integer :year4_cma_id
      t.integer :year5_cma_id
      t.integer :year6_cma_id
      t.integer :year7_cma_id
      t.integer :year8_cma_id
      t.integer :year9_cma_id
      t.integer :year10_cma_id
      t.integer :year11_cma_id
      t.integer :year12_cma_id
      t.integer :year13_cma_id
      t.integer :year14_cma_id
      t.integer :year15_cma_id
      t.integer :year16_cma_id
      t.integer :year17_cma_id
      t.integer :year18_cma_id
      t.integer :year19_cma_id
      t.integer :year20_cma_id
      t.integer :year21_cma_id
      t.integer :year22_cma_id
      t.integer :year23_cma_id
      t.integer :year24_cma_id
      t.integer :year25_cma_id
      t.integer :year26_cma_id
      t.integer :year27_cma_id
      t.integer :year28_cma_id
      t.integer :year29_cma_id
      t.integer :year30_cma_id
      t.integer :year1_correl_id
      t.integer :year2_correl_id
      t.integer :year3_correl_id
      t.integer :year4_correl_id
      t.integer :year5_correl_id
      t.integer :year6_correl_id
      t.integer :year7_correl_id
      t.integer :year8_correl_id
      t.integer :year9_correl_id
      t.integer :year10_correl_id
      t.integer :year11_correl_id
      t.integer :year12_correl_id
      t.integer :year13_correl_id
      t.integer :year14_correl_id
      t.integer :year15_correl_id
      t.integer :year16_correl_id
      t.integer :year17_correl_id
      t.integer :year18_correl_id
      t.integer :year19_correl_id
      t.integer :year20_correl_id
      t.integer :year21_correl_id
      t.integer :year22_correl_id
      t.integer :year23_correl_id
      t.integer :year24_correl_id
      t.integer :year25_correl_id
      t.integer :year26_correl_id
      t.integer :year27_correl_id
      t.integer :year28_correl_id
      t.integer :year29_correl_id
      t.integer :year30_correl_id

      t.timestamps
    end
  end
end
