class ForecastInputsController < ApplicationController
  def index
    matching_forecast_inputs = ForecastInput.all

    @list_of_forecast_inputs = matching_forecast_inputs.order({ :created_at => :desc })

    render({ :template => "forecast_inputs/index.html.erb" })
  end

  def show
    the_id = params.fetch("path_id")

    matching_forecast_inputs = ForecastInput.where({ :id => the_id })

    @the_forecast_input = matching_forecast_inputs.at(0)

    render({ :template => "forecast_inputs/show.html.erb" })
  end

  def create
    the_forecast_input = ForecastInput.new
    the_forecast_input.forecast_id = params.fetch("query_forecast_id")
    the_forecast_input.inflation = params.fetch("query_inflation")
    the_forecast_input.starting_value = params.fetch("query_starting_value")
    the_forecast_input.income = params.fetch("query_income")
    the_forecast_input.spend_value = params.fetch("query_spend_value")
    the_forecast_input.years_income = params.fetch("query_years_income")
    the_forecast_input.years_forecast = params.fetch("query_years_forecast")
    the_forecast_input.portfolio1_id = params.fetch("query_portfolio1_id")
    the_forecast_input.portfolio2_id = params.fetch("query_portfolio2_id")
    the_forecast_input.weight_port1 = params.fetch("query_weight_port1")
    the_forecast_input.weight_port2 = params.fetch("query_weight_port2")
    the_forecast_input.cma_id = params.fetch("query_cma_id")
    the_forecast_input.correlation_id = params.fetch("query_correlation_id")
    the_forecast_input.year1_cf = params.fetch("query_year1_cf")
    the_forecast_input.year2_cf = params.fetch("query_year2_cf")
    the_forecast_input.year3_cf = params.fetch("query_year3_cf")
    the_forecast_input.year4_cf = params.fetch("query_year4_cf")
    the_forecast_input.year5_cf = params.fetch("query_year5_cf")
    the_forecast_input.year6_cf = params.fetch("query_year6_cf")
    the_forecast_input.year7_cf = params.fetch("query_year7_cf")
    the_forecast_input.year8_cf = params.fetch("query_year8_cf")
    the_forecast_input.year9_cf = params.fetch("query_year9_cf")
    the_forecast_input.year10_cf = params.fetch("query_year10_cf")
    the_forecast_input.year11_cf = params.fetch("query_year11_cf")
    the_forecast_input.year12_cf = params.fetch("query_year12_cf")
    the_forecast_input.year13_cf = params.fetch("query_year13_cf")
    the_forecast_input.year14_cf = params.fetch("query_year14_cf")
    the_forecast_input.year15_cf = params.fetch("query_year15_cf")
    the_forecast_input.year16_cf = params.fetch("query_year16_cf")
    the_forecast_input.year17_cf = params.fetch("query_year17_cf")
    the_forecast_input.year18_cf = params.fetch("query_year18_cf")
    the_forecast_input.year19_cf = params.fetch("query_year19_cf")
    the_forecast_input.year20_cf = params.fetch("query_year20_cf")
    the_forecast_input.year21_cf = params.fetch("query_year21_cf")
    the_forecast_input.year22_cf = params.fetch("query_year22_cf")
    the_forecast_input.year23_cf = params.fetch("query_year23_cf")
    the_forecast_input.year24_cf = params.fetch("query_year24_cf")
    the_forecast_input.year25_cf = params.fetch("query_year25_cf")
    the_forecast_input.year26_cf = params.fetch("query_year26_cf")
    the_forecast_input.year27_cf = params.fetch("query_year27_cf")
    the_forecast_input.year28_cf = params.fetch("query_year28_cf")
    the_forecast_input.year29_cf = params.fetch("query_year29_cf")
    the_forecast_input.year30_cf = params.fetch("query_year30_cf")
    the_forecast_input.year1_cma_id = params.fetch("query_year1_cma_id")
    the_forecast_input.year2_cma_id = params.fetch("query_year2_cma_id")
    the_forecast_input.year3_cma_id = params.fetch("query_year3_cma_id")
    the_forecast_input.year4_cma_id = params.fetch("query_year4_cma_id")
    the_forecast_input.year5_cma_id = params.fetch("query_year5_cma_id")
    the_forecast_input.year6_cma_id = params.fetch("query_year6_cma_id")
    the_forecast_input.year7_cma_id = params.fetch("query_year7_cma_id")
    the_forecast_input.year8_cma_id = params.fetch("query_year8_cma_id")
    the_forecast_input.year9_cma_id = params.fetch("query_year9_cma_id")
    the_forecast_input.year10_cma_id = params.fetch("query_year10_cma_id")
    the_forecast_input.year11_cma_id = params.fetch("query_year11_cma_id")
    the_forecast_input.year12_cma_id = params.fetch("query_year12_cma_id")
    the_forecast_input.year13_cma_id = params.fetch("query_year13_cma_id")
    the_forecast_input.year14_cma_id = params.fetch("query_year14_cma_id")
    the_forecast_input.year15_cma_id = params.fetch("query_year15_cma_id")
    the_forecast_input.year16_cma_id = params.fetch("query_year16_cma_id")
    the_forecast_input.year17_cma_id = params.fetch("query_year17_cma_id")
    the_forecast_input.year18_cma_id = params.fetch("query_year18_cma_id")
    the_forecast_input.year19_cma_id = params.fetch("query_year19_cma_id")
    the_forecast_input.year20_cma_id = params.fetch("query_year20_cma_id")
    the_forecast_input.year21_cma_id = params.fetch("query_year21_cma_id")
    the_forecast_input.year22_cma_id = params.fetch("query_year22_cma_id")
    the_forecast_input.year23_cma_id = params.fetch("query_year23_cma_id")
    the_forecast_input.year24_cma_id = params.fetch("query_year24_cma_id")
    the_forecast_input.year25_cma_id = params.fetch("query_year25_cma_id")
    the_forecast_input.year26_cma_id = params.fetch("query_year26_cma_id")
    the_forecast_input.year27_cma_id = params.fetch("query_year27_cma_id")
    the_forecast_input.year28_cma_id = params.fetch("query_year28_cma_id")
    the_forecast_input.year29_cma_id = params.fetch("query_year29_cma_id")
    the_forecast_input.year30_cma_id = params.fetch("query_year30_cma_id")
    the_forecast_input.year1_correl_id = params.fetch("query_year1_correl_id")
    the_forecast_input.year2_correl_id = params.fetch("query_year2_correl_id")
    the_forecast_input.year3_correl_id = params.fetch("query_year3_correl_id")
    the_forecast_input.year4_correl_id = params.fetch("query_year4_correl_id")
    the_forecast_input.year5_correl_id = params.fetch("query_year5_correl_id")
    the_forecast_input.year6_correl_id = params.fetch("query_year6_correl_id")
    the_forecast_input.year7_correl_id = params.fetch("query_year7_correl_id")
    the_forecast_input.year8_correl_id = params.fetch("query_year8_correl_id")
    the_forecast_input.year9_correl_id = params.fetch("query_year9_correl_id")
    the_forecast_input.year10_correl_id = params.fetch("query_year10_correl_id")
    the_forecast_input.year11_correl_id = params.fetch("query_year11_correl_id")
    the_forecast_input.year12_correl_id = params.fetch("query_year12_correl_id")
    the_forecast_input.year13_correl_id = params.fetch("query_year13_correl_id")
    the_forecast_input.year14_correl_id = params.fetch("query_year14_correl_id")
    the_forecast_input.year15_correl_id = params.fetch("query_year15_correl_id")
    the_forecast_input.year16_correl_id = params.fetch("query_year16_correl_id")
    the_forecast_input.year17_correl_id = params.fetch("query_year17_correl_id")
    the_forecast_input.year18_correl_id = params.fetch("query_year18_correl_id")
    the_forecast_input.year19_correl_id = params.fetch("query_year19_correl_id")
    the_forecast_input.year20_correl_id = params.fetch("query_year20_correl_id")
    the_forecast_input.year21_correl_id = params.fetch("query_year21_correl_id")
    the_forecast_input.year22_correl_id = params.fetch("query_year22_correl_id")
    the_forecast_input.year23_correl_id = params.fetch("query_year23_correl_id")
    the_forecast_input.year24_correl_id = params.fetch("query_year24_correl_id")
    the_forecast_input.year25_correl_id = params.fetch("query_year25_correl_id")
    the_forecast_input.year26_correl_id = params.fetch("query_year26_correl_id")
    the_forecast_input.year27_correl_id = params.fetch("query_year27_correl_id")
    the_forecast_input.year28_correl_id = params.fetch("query_year28_correl_id")
    the_forecast_input.year29_correl_id = params.fetch("query_year29_correl_id")
    the_forecast_input.year30_correl_id = params.fetch("query_year30_correl_id")

    if the_forecast_input.valid?
      the_forecast_input.save
      redirect_to("/forecast_inputs", { :notice => "Forecast input created successfully." })
    else
      redirect_to("/forecast_inputs", { :notice => "Forecast input failed to create successfully." })
    end
  end

  def update
    the_id = params.fetch("path_id")
    the_forecast_input = ForecastInput.where({ :id => the_id }).at(0)

    the_forecast_input.forecast_id = params.fetch("query_forecast_id")
    the_forecast_input.inflation = params.fetch("query_inflation")
    the_forecast_input.starting_value = params.fetch("query_starting_value")
    the_forecast_input.income = params.fetch("query_income")
    the_forecast_input.spend_value = params.fetch("query_spend_value")
    the_forecast_input.years_income = params.fetch("query_years_income")
    the_forecast_input.years_forecast = params.fetch("query_years_forecast")
    the_forecast_input.portfolio1_id = params.fetch("query_portfolio1_id")
    the_forecast_input.portfolio2_id = params.fetch("query_portfolio2_id")
    the_forecast_input.weight_port1 = params.fetch("query_weight_port1")
    the_forecast_input.weight_port2 = params.fetch("query_weight_port2")
    the_forecast_input.cma_id = params.fetch("query_cma_id")
    the_forecast_input.correlation_id = params.fetch("query_correlation_id")
    the_forecast_input.year1_cf = params.fetch("query_year1_cf")
    the_forecast_input.year2_cf = params.fetch("query_year2_cf")
    the_forecast_input.year3_cf = params.fetch("query_year3_cf")
    the_forecast_input.year4_cf = params.fetch("query_year4_cf")
    the_forecast_input.year5_cf = params.fetch("query_year5_cf")
    the_forecast_input.year6_cf = params.fetch("query_year6_cf")
    the_forecast_input.year7_cf = params.fetch("query_year7_cf")
    the_forecast_input.year8_cf = params.fetch("query_year8_cf")
    the_forecast_input.year9_cf = params.fetch("query_year9_cf")
    the_forecast_input.year10_cf = params.fetch("query_year10_cf")
    the_forecast_input.year11_cf = params.fetch("query_year11_cf")
    the_forecast_input.year12_cf = params.fetch("query_year12_cf")
    the_forecast_input.year13_cf = params.fetch("query_year13_cf")
    the_forecast_input.year14_cf = params.fetch("query_year14_cf")
    the_forecast_input.year15_cf = params.fetch("query_year15_cf")
    the_forecast_input.year16_cf = params.fetch("query_year16_cf")
    the_forecast_input.year17_cf = params.fetch("query_year17_cf")
    the_forecast_input.year18_cf = params.fetch("query_year18_cf")
    the_forecast_input.year19_cf = params.fetch("query_year19_cf")
    the_forecast_input.year20_cf = params.fetch("query_year20_cf")
    the_forecast_input.year21_cf = params.fetch("query_year21_cf")
    the_forecast_input.year22_cf = params.fetch("query_year22_cf")
    the_forecast_input.year23_cf = params.fetch("query_year23_cf")
    the_forecast_input.year24_cf = params.fetch("query_year24_cf")
    the_forecast_input.year25_cf = params.fetch("query_year25_cf")
    the_forecast_input.year26_cf = params.fetch("query_year26_cf")
    the_forecast_input.year27_cf = params.fetch("query_year27_cf")
    the_forecast_input.year28_cf = params.fetch("query_year28_cf")
    the_forecast_input.year29_cf = params.fetch("query_year29_cf")
    the_forecast_input.year30_cf = params.fetch("query_year30_cf")
    the_forecast_input.year1_cma_id = params.fetch("query_year1_cma_id")
    the_forecast_input.year2_cma_id = params.fetch("query_year2_cma_id")
    the_forecast_input.year3_cma_id = params.fetch("query_year3_cma_id")
    the_forecast_input.year4_cma_id = params.fetch("query_year4_cma_id")
    the_forecast_input.year5_cma_id = params.fetch("query_year5_cma_id")
    the_forecast_input.year6_cma_id = params.fetch("query_year6_cma_id")
    the_forecast_input.year7_cma_id = params.fetch("query_year7_cma_id")
    the_forecast_input.year8_cma_id = params.fetch("query_year8_cma_id")
    the_forecast_input.year9_cma_id = params.fetch("query_year9_cma_id")
    the_forecast_input.year10_cma_id = params.fetch("query_year10_cma_id")
    the_forecast_input.year11_cma_id = params.fetch("query_year11_cma_id")
    the_forecast_input.year12_cma_id = params.fetch("query_year12_cma_id")
    the_forecast_input.year13_cma_id = params.fetch("query_year13_cma_id")
    the_forecast_input.year14_cma_id = params.fetch("query_year14_cma_id")
    the_forecast_input.year15_cma_id = params.fetch("query_year15_cma_id")
    the_forecast_input.year16_cma_id = params.fetch("query_year16_cma_id")
    the_forecast_input.year17_cma_id = params.fetch("query_year17_cma_id")
    the_forecast_input.year18_cma_id = params.fetch("query_year18_cma_id")
    the_forecast_input.year19_cma_id = params.fetch("query_year19_cma_id")
    the_forecast_input.year20_cma_id = params.fetch("query_year20_cma_id")
    the_forecast_input.year21_cma_id = params.fetch("query_year21_cma_id")
    the_forecast_input.year22_cma_id = params.fetch("query_year22_cma_id")
    the_forecast_input.year23_cma_id = params.fetch("query_year23_cma_id")
    the_forecast_input.year24_cma_id = params.fetch("query_year24_cma_id")
    the_forecast_input.year25_cma_id = params.fetch("query_year25_cma_id")
    the_forecast_input.year26_cma_id = params.fetch("query_year26_cma_id")
    the_forecast_input.year27_cma_id = params.fetch("query_year27_cma_id")
    the_forecast_input.year28_cma_id = params.fetch("query_year28_cma_id")
    the_forecast_input.year29_cma_id = params.fetch("query_year29_cma_id")
    the_forecast_input.year30_cma_id = params.fetch("query_year30_cma_id")
    the_forecast_input.year1_correl_id = params.fetch("query_year1_correl_id")
    the_forecast_input.year2_correl_id = params.fetch("query_year2_correl_id")
    the_forecast_input.year3_correl_id = params.fetch("query_year3_correl_id")
    the_forecast_input.year4_correl_id = params.fetch("query_year4_correl_id")
    the_forecast_input.year5_correl_id = params.fetch("query_year5_correl_id")
    the_forecast_input.year6_correl_id = params.fetch("query_year6_correl_id")
    the_forecast_input.year7_correl_id = params.fetch("query_year7_correl_id")
    the_forecast_input.year8_correl_id = params.fetch("query_year8_correl_id")
    the_forecast_input.year9_correl_id = params.fetch("query_year9_correl_id")
    the_forecast_input.year10_correl_id = params.fetch("query_year10_correl_id")
    the_forecast_input.year11_correl_id = params.fetch("query_year11_correl_id")
    the_forecast_input.year12_correl_id = params.fetch("query_year12_correl_id")
    the_forecast_input.year13_correl_id = params.fetch("query_year13_correl_id")
    the_forecast_input.year14_correl_id = params.fetch("query_year14_correl_id")
    the_forecast_input.year15_correl_id = params.fetch("query_year15_correl_id")
    the_forecast_input.year16_correl_id = params.fetch("query_year16_correl_id")
    the_forecast_input.year17_correl_id = params.fetch("query_year17_correl_id")
    the_forecast_input.year18_correl_id = params.fetch("query_year18_correl_id")
    the_forecast_input.year19_correl_id = params.fetch("query_year19_correl_id")
    the_forecast_input.year20_correl_id = params.fetch("query_year20_correl_id")
    the_forecast_input.year21_correl_id = params.fetch("query_year21_correl_id")
    the_forecast_input.year22_correl_id = params.fetch("query_year22_correl_id")
    the_forecast_input.year23_correl_id = params.fetch("query_year23_correl_id")
    the_forecast_input.year24_correl_id = params.fetch("query_year24_correl_id")
    the_forecast_input.year25_correl_id = params.fetch("query_year25_correl_id")
    the_forecast_input.year26_correl_id = params.fetch("query_year26_correl_id")
    the_forecast_input.year27_correl_id = params.fetch("query_year27_correl_id")
    the_forecast_input.year28_correl_id = params.fetch("query_year28_correl_id")
    the_forecast_input.year29_correl_id = params.fetch("query_year29_correl_id")
    the_forecast_input.year30_correl_id = params.fetch("query_year30_correl_id")

    if the_forecast_input.valid?
      the_forecast_input.save
      redirect_to("/forecast_inputs/#{the_forecast_input.id}", { :notice => "Forecast input updated successfully."} )
    else
      redirect_to("/forecast_inputs/#{the_forecast_input.id}", { :alert => "Forecast input failed to update successfully." })
    end
  end

  def destroy
    the_id = params.fetch("path_id")
    the_forecast_input = ForecastInput.where({ :id => the_id }).at(0)

    the_forecast_input.destroy

    redirect_to("/forecast_inputs", { :notice => "Forecast input deleted successfully."} )
  end
end
